schedules:
- cron: "0 3 * * Mon"
  displayName: Weekly build
  branches:
    include:
    - master
  always: true

jobs:
- job: 'ParallelTesting'
  pool:
    vmImage: 'ubuntu-18.04'
  strategy:
    parallel: 5
  displayName: Run tests in parallel

  steps:
  - task: UseDotNet@2
    displayName: 'Use .NET Core sdk 6.0.x'
    inputs:
      version: 6.0.x
      performMultiLevelLookup: true
      
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: build
      projects: '**/*.csproj'

  - bash: |
      tests=($(dotnet test . --no-build --list-tests | grep Test_))
      . 'create_slicing_filter_condition.sh' $tests
    displayName: 'Create slicing filter condition'
  
  - bash: |
      echo "Slicing filter condition: $(targetTestsFilter)"
    displayName: 'Echo slicing filter condition'

  - task: DotNetCoreCLI@2
    displayName: Test
    inputs:
      command: test
      projects: '**/*Tests/*Tests.csproj'
      arguments: '--no-build --filter "$(targetTestsFilter)"'